//https://marketplace.visualstudio.com/items?itemName=humao.rest-client&ssr=false#overview
Environment Variables
For environment variables, each environment comprises a set of key value pairs defined in setting file, key and value are variable name and value respectively. Only variables defined in selected environment and shared environment are available to you. You can also reference the variables in shard environment with {{$shared variableName}} syntax in your active environment. Below is a sample piece of setting file for custom environments and environment level variables:

"rest-client.environmentVariables": {
    "$shared": {
        "version": "v1",
        "prodToken": "foo",
        "nonProdToken": "bar"
    },
    "local": {
        "version": "v2",
        "host": "localhost",
        "token": "{{$shared nonProdToken}}",
        "secretKey": "devSecret"
    },
    "production": {
        "host": "example.com",
        "token": "{{$shared prodToken}}",
        "secretKey" : "prodSecret"
    }
}
A sample usage in http file for above environment variables is listed below, note that if you switch to local environment, the version would be v2, if you change to production environment, the version would be v1 which is inherited from the $shared environment:

GET https://{{host}}/api/{{version}}comments/1 HTTP/1.1
Authorization: {{token}}

###
# we changed to the following:
{
  "rest-client.environmentVariables": {
    "sandbox": {
      "baseUrl": "https://apigw.nubentos.com:443",
      "authorization": "YouKeys",
      "accessToken": "91744c1d-fd94-35a4-b855-b22964faf1a5"
    },
    "production": {

    }
  }
}

# Used to get an access token given an autorization key

#  curl -k -d "grant_type=client_credentials" \
#	    -H "Authorization: Basic YourKeyHere" \
#	      https://apigw.nubentos.com:443/token

#//https://apigw.nubentos.com:443/token?grant_type=client_credentials
#//[ base url: /t/nubentos.com/ncovapi/2.0.0 , api version: 1.0.0 ]
Send Request
POST {{baseUrl}}/token?grant_type=client_credentials
Authorization: Basic {{authorization}}

###
# in settings.json: "baseUrl": "https://apigw.nubentos.com:443"
GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/cases
Accept: application/json
Authorization: Bearer: {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/cases/deaths
Accept: application/json
Authorization: Bearer: {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/active
Accept: application/json
Authorization: Bearer: {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/recovered
Accept: application/json
Authorization: Bearer: {{accessToken}}

###


GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/todayCases
Accept: application/json
Authorization: Bearer: {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/todayDeaths
Accept: application/json
Authorization: Bearer: {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/totalTests
Accept: application/json
Authorization: Bearer: {{accessToken}}
